CREATE TABLE IF NOT EXISTS gallery (
  gid INTEGER PRIMARY KEY,
  token TEXT NOT NULL,
  archiver_key TEXT,
  title TEXT NOT NULL,
  title_jpn TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL,
  thumb TEXT NOT NULL,
  uploader TEXT,
  posted INTEGER NOT NULL,
  filecount INTEGER NOT NULL,
  filesize INTEGER NOT NULL,
  expunged INTEGER NOT NULL,
  removed INTEGER NOT NULL DEFAULT 0,
  replaced INTEGER NOT NULL DEFAULT 0,
  rating TEXT NOT NULL,
  torrentcount INTEGER NOT NULL,
  root_gid INTEGER DEFAULT NULL,
  bytorrent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gid_tid (
  gid INTEGER NOT NULL,
  tid INTEGER NOT NULL,
  PRIMARY KEY (gid, tid)
);

CREATE TABLE IF NOT EXISTS tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS torrent (
  id INTEGER PRIMARY KEY,
  gid INTEGER NOT NULL,
  name TEXT NOT NULL,
  hash TEXT,
  addedstr TEXT,
  fsizestr TEXT,
  uploader TEXT NOT NULL,
  expunged INTEGER NOT NULL DEFAULT 0
);
